[package]
name = "sbml-parser-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_derive = "1.0.217"
quick-xml = "0.37.2"
quote = "1.0.38"
syn = "2.0.96"

[lib]
proc-macro = true
