[package]
name = "sbml-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.37.2", features = ["serialize"] }
serde = { version = "1.0.217", features = [ "derive" ] }
sbml-parser-macro = { path = "../sbml-parser-macro" }
serde_json = "1.0.136"
serde-lexpr = "0.1.3"
